site_name: Nubomedia Graph Editor
pages:
- Home: index.md
- 'Installation Guide': installation.md
- 'Codegen Installation Guide': codegeninstall.md
- 'Developers Guide': developers.md
- 'Reference Manual': reference.md
- 'Software Architecture': architecture.md
theme: readthedocs
extra_css: [extra.css]